# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpSim < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/espetro/mcp-sim/releases/download/v0.1.1/mcp-sim_0.1.1_darwin_amd64.zip"
      sha256 "c6ed0fccb83958596f8a6efb1a3f0f3a481e580633485e5b8822466c348ce62b"

      define_method(:install) do
        bin.install "mcp-sim"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/espetro/mcp-sim/releases/download/v0.1.1/mcp-sim_0.1.1_darwin_arm64.zip"
      sha256 "2c5f111de5e5e070833f708f4228adfac4b858f324958f660519a25e08b260e0"

      define_method(:install) do
        bin.install "mcp-sim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/espetro/mcp-sim/releases/download/v0.1.1/mcp-sim_0.1.1_linux_amd64.tar.gz"
      sha256 "d810ecba9c6cf024518025894234571b190e630ea64168c5b9bb49460096c437"
      define_method(:install) do
        bin.install "mcp-sim"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/espetro/mcp-sim/releases/download/v0.1.1/mcp-sim_0.1.1_linux_arm64.tar.gz"
      sha256 "006b8a5e3afb06203061162e181bf2b0c55e80b9cf6d69547bbef06b7cc3c29b"
      define_method(:install) do
        bin.install "mcp-sim"
      end
    end
  end

  service do
    run [opt_bin/"mcp-sim", "serve", "--listen", ":9090"]
    keep_alive true
    log_path var/"log/mcp-sim.log"
    error_log_path var/"log/mcp-sim.log"
  end

  test do
    system "#{bin}/mcp-sim version"
  end
end
