# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpSim < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/espetro/mcp-sim/releases/download/v0.2.0/mcp-sim_0.2.0_darwin_amd64.zip"
      sha256 "6f97b0ab3337c0be1d1f97f8aa8a06ecc8e4a519c9113d771fe2b08f7cd937a9"

      define_method(:install) do
        bin.install "mcp-sim"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/espetro/mcp-sim/releases/download/v0.2.0/mcp-sim_0.2.0_darwin_arm64.zip"
      sha256 "cf755fa2196f520bcef46a0e5ebc8fe2095b50e497a49479cb541adef1412811"

      define_method(:install) do
        bin.install "mcp-sim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/espetro/mcp-sim/releases/download/v0.2.0/mcp-sim_0.2.0_linux_amd64.tar.gz"
      sha256 "bd3787ca05c03f4fc0d99921e94660d7ae9b297c807806750688fe66ea056286"
      define_method(:install) do
        bin.install "mcp-sim"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/espetro/mcp-sim/releases/download/v0.2.0/mcp-sim_0.2.0_linux_arm64.tar.gz"
      sha256 "888521d99fc879b6c2597bd9be9ebeead2c1bb3e06a3f647895c7c0a0e6c2135"
      define_method(:install) do
        bin.install "mcp-sim"
      end
    end
  end

  service do
    run [opt_bin/"mcp-sim", "serve", "--listen", ":9090"]
    keep_alive true
    log_path var/"log/mcp-sim.log"
    error_log_path var/"log/mcp-sim.log"
  end

  test do
    system "#{bin}/mcp-sim version"
  end
end
